#!/usr/bin/env python3
"""Create an independently-defined XLSX v2 text/object fixture and frozen probes."""
from __future__ import annotations
import argparse, hashlib, json, zipfile
from pathlib import Path

PNG = bytes.fromhex("89504e470d0a1a0a0000000d4948445200000001000000010804000000b51c0c020000000b4944415478da6364f80f00010501012718e3660000000049454e44ae426082")
TOKENS = [
 "VISIBLE_ALPHA","VISIBLE_日本語","VISIBLE_追加","HIDDEN_ALPHA","HIDDEN_繁體","RICH_EN","RICH_日本語","RICH_漢字",
 "DRAWING_ONE","DRAWING_TWO","DRAWING_THREE","DRAWING_四","VML_ONE","VML_TWO","VML_THREE","VML_四",
 "COMMENT_ONE","COMMENT_TWO","COMMENT_日本語","COMMENT_四","THREAD_ONE","THREAD_TWO","THREAD_日本語","THREAD_四",
 "ABSOLUTE_ONE","ABSOLUTE_TWO","ABSOLUTE_THREE","ABSOLUTE_四","GROUP_ONE","GROUP_TWO","GROUP_THREE","GROUP_四",
 "GROUP_NESTED_ONE","GROUP_NESTED_TWO","GROUP_NESTED_THREE","GROUP_NESTED_四","ENTITY_&<>\"'",
 "ASSET_INTERNAL","ASSET_EXTERNAL",
]
def main():
 p=argparse.ArgumentParser(); p.add_argument('--output',type=Path,required=True); a=p.parse_args(); out=a.output; out.parent.mkdir(parents=True,exist_ok=True)
 parts={
 '[Content_Types].xml': '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="png" ContentType="image/png"/><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Default Extension="vml" ContentType="application/vnd.openxmlformats-officedocument.vmlDrawing"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/worksheets/sheet2.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/comments1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.comments+xml"/><Override PartName="/xl/drawings/drawing1.xml" ContentType="application/vnd.openxmlformats-officedocument.drawing+xml"/><Override PartName="/xl/threadedComments/threadedComment1.xml" ContentType="application/vnd.ms-excel.threadedcomments+xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/></Types>',
 '_rels/.rels':'<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="workbook" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>',
 'xl/workbook.xml':'<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Visible" sheetId="1" r:id="rId1"/><sheet name="Hidden" state="hidden" sheetId="2" r:id="rId2"/></sheets></workbook>',
 'xl/_rels/workbook.xml.rels':'<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet2.xml"/></Relationships>',
 'xl/worksheets/sheet1.xml':'<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheetData><row r="1"><c r="A1" t="inlineStr"><is><t>VISIBLE_ALPHA VISIBLE_日本語 VISIBLE_追加 RICH_EN RICH_日本語 RICH_漢字</t></is></c></row></sheetData><drawing r:id="d"/><legacyDrawing r:id="v"/></worksheet>',
 'xl/worksheets/sheet2.xml':'<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData><row r="1"><c r="A1" t="inlineStr"><is><t>HIDDEN_ALPHA HIDDEN_繁體</t></is></c></row></sheetData></worksheet>',
 'xl/worksheets/_rels/sheet1.xml.rels':'<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="d" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/drawing" Target="../drawings/drawing1.xml"/><Relationship Id="v" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/vmlDrawing" Target="../drawings/vml1.vml"/><Relationship Id="c" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/comments" Target="../comments1.xml"/><Relationship Id="t" Type="http://schemas.microsoft.com/office/2017/10/relationships/threadedComment" Target="../threadedComments/threadedComment1.xml"/></Relationships>',
 'xl/comments1.xml':'<comments xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><authors><author>Fixture Author</author></authors><commentList><comment ref="B2" authorId="0"><text><t>COMMENT_ONE COMMENT_TWO COMMENT_日本語 COMMENT_四 ENTITY_&amp;&lt;&gt;&quot;&apos;</t></text></comment></commentList></comments>',
 'xl/threadedComments/threadedComment1.xml':'<ThreadedComments xmlns="http://schemas.microsoft.com/office/spreadsheetml/2018/threadedcomments"><threadedComment ref="C3" personId="person-1"><text>THREAD_ONE THREAD_TWO THREAD_日本語 THREAD_四</text></threadedComment></ThreadedComments>',
 'xl/drawings/drawing1.xml':'<xdr:wsDr xmlns:xdr="http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><xdr:twoCellAnchor><xdr:from><xdr:col>1</xdr:col><xdr:row>1</xdr:row></xdr:from><xdr:to><xdr:col>2</xdr:col><xdr:row>3</xdr:row></xdr:to><xdr:sp><xdr:nvSpPr><xdr:cNvPr id="77" name="Direct textbox"/><xdr:cNvSpPr txBox="1"/></xdr:nvSpPr><xdr:spPr/><xdr:txBody><a:bodyPr/><a:lstStyle/><a:p><a:r><a:t>DRAWING_ONE DRAWING_TWO</a:t></a:r></a:p><a:p><a:r><a:t>DRAWING_THREE DRAWING_四</a:t></a:r></a:p></xdr:txBody></xdr:sp><xdr:clientData/></xdr:twoCellAnchor><xdr:oneCellAnchor><xdr:from><xdr:col>10</xdr:col><xdr:row>10</xdr:row></xdr:from><xdr:ext cx="9525" cy="9525"/><xdr:pic><xdr:nvPicPr><xdr:cNvPr id="99" name="Image"/><xdr:cNvPicPr/></xdr:nvPicPr><xdr:blipFill><a:blip r:embed="img"/></xdr:blipFill></xdr:pic><xdr:clientData/></xdr:oneCellAnchor><xdr:absoluteAnchor><xdr:pos x="914400" y="1828800"/><xdr:ext cx="2743200" cy="3657600"/><xdr:sp><xdr:nvSpPr><xdr:cNvPr id="88" name="Absolute textbox"/><xdr:cNvSpPr txBox="1"/></xdr:nvSpPr><xdr:spPr/><xdr:txBody><a:bodyPr/><a:lstStyle/><a:p><a:r><a:t>ABSOLUTE_ONE</a:t></a:r><a:br/><a:r><a:t>ABSOLUTE_TWO</a:t></a:r><a:tab/><a:r><a:t>ABSOLUTE_THREE ABSOLUTE_四</a:t></a:r></a:p></xdr:txBody></xdr:sp><xdr:clientData/></xdr:absoluteAnchor><xdr:twoCellAnchor><xdr:from><xdr:col>6</xdr:col><xdr:row>7</xdr:row></xdr:from><xdr:to><xdr:col>8</xdr:col><xdr:row>9</xdr:row></xdr:to><xdr:grpSp><xdr:sp><xdr:nvSpPr><xdr:cNvPr id="91" name="Group textbox"/><xdr:cNvSpPr txBox="1"/></xdr:nvSpPr><xdr:spPr/><xdr:txBody><a:bodyPr/><a:lstStyle/><a:p><a:r><a:t>GROUP_ONE GROUP_TWO GROUP_THREE GROUP_四</a:t></a:r></a:p></xdr:txBody></xdr:sp><xdr:grpSp><xdr:sp><xdr:nvSpPr><xdr:cNvPr id="92" name="Nested textbox"/><xdr:cNvSpPr txBox="1"/></xdr:nvSpPr><xdr:spPr/><xdr:txBody><a:bodyPr/><a:lstStyle/><a:p><a:r><a:t>GROUP_NESTED_ONE GROUP_NESTED_TWO GROUP_NESTED_THREE GROUP_NESTED_四</a:t></a:r></a:p></xdr:txBody></xdr:sp></xdr:grpSp></xdr:grpSp><xdr:clientData/></xdr:twoCellAnchor></xdr:wsDr>',
 'xl/drawings/_rels/drawing1.xml.rels':'<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="img" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="../media/image1.png"/><Relationship Id="external" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="https://example.invalid/external.png" TargetMode="External"/></Relationships>',
 'xl/drawings/vml1.vml':'<xml xmlns:v="urn:schemas-microsoft-com:vml" xmlns:x="urn:schemas-microsoft-com:office:excel"><v:shape id="vml77"><v:textbox>VML_ONE VML_TWO VML_THREE VML_四 ENTITY_&amp;&lt;&gt;&quot;&apos;</v:textbox><x:ClientData ObjectType="TextBox"><x:Row>4</x:Row><x:Column>5</x:Column></x:ClientData></v:shape></xml>',
 }
 # OPC package metadata is complete; probe text remains unchanged.
 with zipfile.ZipFile(out,'w',zipfile.ZIP_DEFLATED) as z:
  for k,v in parts.items(): z.writestr(k,v)
  z.writestr('xl/media/image1.png',PNG)
 probes={'schema':1,'oracle':'literal constants in this generator; native output is never an oracle','fixture':out.name,'probes':[{'text':x,'source':'literal OOXML non-cell text'} for x in TOKENS[8:-2]]}
 probe=out.with_suffix('.probes.json'); probe.write_text(json.dumps(probes,ensure_ascii=False,indent=2)+'\n')
 print(json.dumps({'fixture':str(out),'sha256':hashlib.sha256(out.read_bytes()).hexdigest(),'probes':str(probe),'probeSha256':hashlib.sha256(probe.read_bytes()).hexdigest(),'probeCount':len(probes['probes'])}))
if __name__=='__main__': main()
